# **Python Datacamp**

# **Day 1. Part 2**

## *Dr Kirils Makarovs*

## *k.makarovs@exeter.ac.uk*

## *University of Exeter Q-Step Centre*

---

# **Welcome to Part 2 of Day 1!**

## **Now, we are going to look at the:**

+ Properties of a dataset
+ How to subset datasets
+ How to create new variables

<figure>
<left>
<img src=https://miro.medium.com/max/502/1*sXs3TvhjvXcVCTldKnwMpA.png  width="400">
</figure>

In [ ]:
# Import the necessary libraries

import pandas as pd # data analysis and management library
import numpy as np # multi-dimensional arrays
import math # library with math-related commands like square root, etc.

---

# **1. Pandas. Working with dataframes in Python**

<figure>
<left>
<img src=https://miro.medium.com/max/481/1*n_ms1q5YoHAQXXUIfeADKQ.png  width="450">
</figure>

## **1.2. Getting to know a dataframe in Pandas**

This is how a typical dataset looks like:

<figure>
<left>
<img src=https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png width="550">
</figure>

**[Image source](https://www.geeksforgeeks.org/python-pandas-dataframe/)**

In [ ]:
# Let's create a dataset with the following columns:

# Name of a staff
# Life satisfaction on the scale from 0 to 10
# Whether they were in the office last Tuesday
# Job type
# Their body temperature

# I additionaly set indeces (i.e. row names) with the index argument.

df = pd.DataFrame(data = {'name' : ['Michael', 'Dwight', 'Jim', 'Pam', 'Erin', 'Kevin', 'Andy', 'Angela'],
                          'life_satisfaction' : [5, 9, 7, 7, 8, 5, 10, 4],
                          'tuesday' : [True, False, False, False, True, True, True, True],
                          'job' : ['manager', 'sales', 'sales', 'sales', 'receptionist', 'accounting', 'sales', 'accounting'],
                          'temperature' : [36.8, 37.1, 36.1, 36.6, 38.2, 39.1, 36.5, 36.9]
                          },
                  index = ['MS', 'DS', 'JH', 'PB', 'EH', 'KM', 'AB', 'AM']
                  )

df

In [ ]:
# Some helpful commands to get to know the dataset

type(df) # object type - pandas.core.frame.DataFrame

df.shape # number of rows and columns

df.columns # column names

df.index # indeces

df.info() # summary of the variables in the dataset

# Some common types of variables in Python:
# object - text data
# int64 - numerical data without decimals
# float64 - numerical data with decimals 
# bool - Boolean data (True / False)

df.head() # get the top 5 rows of the dataset

df.tail() # get the last 5 rows of the dataset

df.describe() # picks out only numerical variables (Dtype int64 or float64)
# and shows basic descriptive statistics

## **1.3. Subsetting dataframes via `.loc[]` and `.iloc[]` methods**

<figure>
<left>
<img src=https://static.javatpoint.com/python/images/lists-indexing-and-splitting.png width="400">
</figure>

**[Image source](https://www.analyticsvidhya.com/blog/2021/06/15-functions-you-should-know-to-master-lists-in-python/)**

| Command | Description |
| ------ | ----------- |
| `.iloc[]`   | position-based subsetting |
| `.loc[]` | label-based subsetting |

### **Using `.iloc[]` to navigate a dataframe by row and column numbers**

In [ ]:
# The general structure is the following: df.iloc[rows, columns]

# Selecting columns

df.iloc[:, 0] # select first column and all rows (remember that Python starts counting from 0!)

df.iloc[:, 1:3] # select 2nd and 3rd columns and all rows

df.iloc[:, -2:] # select last 2 columns and all rows

df.iloc[:, [0, 1, 4]] # select the 1st, 2nd, and 5th columns and all rows

# Selecting rows

df.iloc[:4, :] # select first 4 rows and all columns

df.iloc[[0, 3, 7], :] # select 1st, 4th, and 8th rows and all columns

# Selecting rows and columns

df.iloc[0:6, 1:4] # select first 5 rows and columns from 2 to 4

df.iloc[[1, 5, 7], [0, 2, 4]] # 2nd, 6th, and 8th rows and 1st, 3rd, and 5th columns

### **Using `.loc[]` to navigate a dataframe by row and column names**

In [ ]:
# Generally, .loc[] method is more helpful than the .iloc[] one
# as you usually want to pick variables (and, less commonly, rows) by their names
# rather than their position in the dataframe

df.loc[:, 'name'] # select the variable of name. Also try df.loc[:, ['name']]

# When selecting columns, you can simply use: df['name'] or df[['name']]

df[['name', 'tuesday', 'temperature']] # selecting three variables

# This is the same as:
df.loc[:, ['name', 'tuesday', 'temperature']]

df.drop(['name'], axis = 1) # keep all variables except name.
# axis = 1 means that .drop() method will look for 'name' among column names
# axis = 0 would imply search among row names

In [ ]:
# Selecting rows by their indeces - same principle

df.loc[['MS', 'DS', 'AM'], :] # three rows, all variables

df.drop(['AM'], axis = 0) # keep all rows except AM

In [ ]:
# Finally you can combine row and column selection via .loc[]

df.loc[['MS', 'EH'], ['life_satisfaction', 'temperature']]

## **2.4. Subsetting dataframes based on the values of variables**

In [ ]:
# Let's get the dataset once again

df

In [ ]:
# This involves working with .loc[] method and using logical statements

# Say we need to select only those people who work in sales
# This is the same as saying that we need to keep all columns
# and select only those rows (people) who have 'sales' in job variable

# First, try running this:
# Each row of the dataset is tested whether its value of job variable is equal to 'sales'

df['job'] == 'sales'

# Now if you plug this into .loc[] method, you will be able to select
# only those rows, that got True value i.e. they work in sales

df.loc[df['job'] == 'sales' , :] # select only those who work in sales and keep all columns

# For short, this can also be done as df.loc[df['job'] == 'sales']

df.loc[df['job'] == 'sales']

# Or even shorter: df[df['job'] == 'sales']

df[df['job'] == 'sales']

# You can test more than one condition at the same time, but then each one of them
# should be put in round brackets and concatenated either with & or |

# & in Pandas means AND
# | in Pandas means OR (see image below)

# So, say we want to keep only those people who work in sales
# AND whose level of life satisfaction is above 5

# Here is how you can test these two condition

(df['job'] == 'sales') & (df['life_satisfaction'] > 5)

# And this is how you use them with .loc[]

df.loc[(df['job'] == 'sales') | (df['life_satisfaction'] > 5), :]

# Selecting those who are either manager or accountant

df.loc[(df['job'] == 'manager') | (df['job'] == 'accounting'), :]

<figure>
<left>
<img src=https://www.lotame.com/wp-content/uploads/2016/07/BooleanLogic_NR.jpg  width="500">
</figure>

In [ ]:
# You can use .isin() method instead of multiple OR conditions if you want to select more than one category from a single variable

# Same as a last example above, but via .isin() method

df.loc[df['job'].isin(['manager', 'accounting'])]

# Shorter:

df[df['job'].isin(['manager', 'accounting'])]

In [ ]:
# You can filter out boolean variables - those that get only True or False values - in the following way:

# Keep only those people that have True in tuesday variable

# This is the most explicit option:

df.loc[df['tuesday'] == True, : ]

# These options also work:

df[df['tuesday'] == True]

df[df['tuesday']]

# If you want to keep those who have False in a boolean variable:

df.loc[df['tuesday'] != True] # same as '== False'

df[df['tuesday'] != True]

## **Exercise 1**

Alright, time to practice!

*Please select the following subsets of the `df` dataframe:*

> 1. all people and only the variables of `name` and `life_satisfaction`
> 1. people, whose `temperature` is below or equal to 36.6
> 2. people, who **do not** work in sales
> 3. people, whose life satisfaction is above 7 **or** who were in on Tuesday
> 4. people, whose life satisfaction is above the median, **and** the temperature is above the mean
> 5. Michael, Jim, and Pam, and keep only `life_satisfaction` and `temperature` variables

*(Feel free to create a new code cell per each task so you could clearly see the output dataset)*

In [ ]:
# The dataset:

df

In [ ]:
# 1. All people and only the variables of 'name' and 'life_satisfaction'

df.loc[:, ['name', 'life_satisfaction']]

In [ ]:
# 2. People, whose temperature is below or equal 36.6

df.loc[df['temperature'] <= 36.6, :]

# Shorter:

df[df['temperature'] <= 36.6]

In [ ]:
# 3. People, who do not work in sales

df.loc[df['job'] != 'sales', :]

# Shorter:

df[df['job'] != 'sales']

In [ ]:
# 4. People, whose life satisfaction is above 7 OR who were in on Tuesday

df.loc[(df['life_satisfaction'] > 7) | (df['tuesday'] == True), :]

# Shorter:

df[(df['life_satisfaction'] > 7) | df['tuesday'] == True]

In [ ]:
# 5. People, whose life satisfaction is above the median, AND the temperature is above the mean

# Median life satisfaction:
median_ls = df['life_satisfaction'].median()

median_ls

# Mean temperature:
mean_temp = df['temperature'].mean()

mean_temp

df.loc[(df['life_satisfaction'] > median_ls) | (df['temperature'] > mean_temp), :]

# Shorter:

df[(df['life_satisfaction'] > median_ls) & (df['temperature'] > mean_temp)]

In [ ]:
# 6. Michael, Jim, and Pam, and keep only life_satisfaction and temperature variables

df.loc[df['name'].isin(['Michael', 'Jim', 'Pam']), ['name', 'life_satisfaction', 'temperature']]

# **2.5. Creating new variables in a dataframe**

In [ ]:
# The dataset:

df

In [ ]:
# When creating a new variable, the dataframe is automatically updated

df['random_column'] = 'a value'

df

df['id_number'] = np.arange(start = 1, stop = 9, step = 1) # 1, 2, 3, 4, 5, 6, 7, 8

df

# Dropping useless variables

df.drop(['random_column', 'id_number'], axis = 1, inplace = True)


# axis = 1 means searching for these names in column names (axis = 0 would search in row names)

# Note the inplace = True argument
# Its default value is False
# If False, return a copy. Otherwise, do operation inplace and return None.

# 'inplace' argument applies to many of the pandas methods and functions, so keep an eye on the documentation!

df

In [ ]:
# Let me add two new variables called income_year_1, and income_year_2

# Derive 8 random values from the normal distribution which has a mean value of 35000 and sd of 10000,
# and then round up the values up to 1 decimal

df['income_year_1'] = np.random.normal(35000, 10000, 8).round(1)

df['income_year_2'] = np.random.normal(35000, 10000, 8).round(1)

df

# Variable of total income

df['total_income'] = df['income_year_1'] + df['income_year_2']

df

# Less manual way
# df['total_income_2'] = df[['income_year_1', 'income_year_2']].sum(axis = 1)

# Variable of mean income

df['mean_income'] = df[['income_year_1', 'income_year_2']].mean(axis = 1)

df

### **Using `np.where()` to test a single if-else condition**

`np.where()` has the following structure: *`(logical condition, value of True, value if False)`*

In [ ]:
# The dataset:

df

In [ ]:
# Creating a new variable called 'sales' that will have True for everyone who works in sales,
# and False for others

df['sales'] = np.where(df['job'] == 'sales', True, False)

df

# Creating a new variable called 'life_satisfaction_binary' that will have 'High LS' value
# for everyone whose LS is above or equals 5, and 'Low LS' for others

df['ls_binary'] = np.where(df['life_satisfaction'] >= 5, 'High', 'Low')

df

# Creating a new variable called 'satisfied_and_healthy' that will have True value
# for everyone who's got LS value higher than the mean office value AND whose body temperature is strictly 36.6

# Mean office life satisfaction:
mean_ls = df['life_satisfaction'].mean()

df['satisfied_and_healthy'] = np.where((df['life_satisfaction'] > mean_ls) & (df['temperature'] == 36.6), True, False)

df

# Creating a new variable called 'is_rich' that will have 'YES' value
# for everyone whose total income is above the average total income in the office, and 'NO' for all others

df['is_rich'] = np.where(df['total_income'] > df['total_income'].mean(), 'YES', 'NO')

df

# Getting rid of unnecessary variables

df.drop(['is_rich', 'satisfied_and_healthy', 'ls_binary'], axis = 1, inplace = True)

df

## **Exercise 2**

Time to practice!

*Please create the following variables in the `df` dataframe:*

> 1. `need_hospital`, that gets the value `True` if `temperature` is above 38, and `False` for others
> 2. `income_comparison`, that gets the value `'Year 1'` if income in the first year is higher than in the second year, and the value `'Year 2'` if the opposite
> 3. `happy_people`, that gets the value `'super happy'` if it's Michael or anyone else with life satisfaction of 9 or 10, and `'not really'` for all others


*(Feel free to create a new code cell per each task so you could clearly see the output dataset)*

In [ ]:
# The dataset

df

In [ ]:
# 1. `need_hospital`, that gets the value `True` if `temperature` is above 38, and `False` for others

df['need_hospital'] = np.where(df['temperature'] > 38, True, False)

df[['temperature', 'need_hospital']]

In [ ]:
# 2. `income_comparison`, that gets the value 'Year 1' if income in the first year is higher than in the second year,
# and the value 'Year 2' if the opposite

df['income_comparison'] = np.where(df['income_year_1'] > df['income_year_2'], 'Year 1', 'Year 2')

df[['income_year_1', 'income_year_2', 'income_comparison']]

In [ ]:
# `happy_people`, that gets the value `'super happy'` if it's Michael or anyone else with life satisfaction of 9 or 10,
# and `'not really'` for all others

df['happy_people'] = np.where((df['name'] == 'Michael') | df['life_satisfaction'].isin([9, 10]), 'super happy', 'not really')

df[['name', 'life_satisfaction', 'happy_people']]

# **That's the end of Part 2 of Day 1!**